version: '3'
services:
  web:
    build: .
    command: sh -c "yarn install && bundle exec rails webpacker:compile && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rorBooks
    ports:
      - "3000:3000"
    env_file:
      - .env